%% wiring_test.m — 3-frame OLLA wiring verification (~10 seconds)
% Pass criterion: [OLLA] lines appear → getMCSIndexOffset is being called.
% Each ACK should produce: offset 0.000 → -0.030 (StepDown=0.03).
% Each NACK (if any) should produce: offset X → X+0.270 (StepUp=0.27).

projectRoot = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(projectRoot, 'wirelessnetwork')), '-begin');
addpath(genpath(fullfile(projectRoot, '5g')),              '-begin');
wirelessnetworkSupportPackageCheck

rng("default")
sim = wirelessNetworkSimulator.init;

gNB = nrGNB( ...
    Position             = [0 0 30], ...
    TransmitPower        = 60, ...
    CarrierFrequency     = 4.9e9, ...
    ChannelBandwidth     = 10e6, ...
    SubcarrierSpacing    = 30e3, ...
    NumResourceBlocks    = 24, ...
    NumTransmitAntennas  = 4, ...
    NumReceiveAntennas   = 4, ...
    DuplexMode           = "TDD", ...
    ReceiveGain          = 11, ...
    SRSPeriodicityUE     = 20);

oLLA = struct('InitialOffset', 0, 'StepUp', 0.27, 'StepDown', 0.03);

configureScheduler(gNB, ...
    ResourceAllocationType  = 0, ...
    MaxNumUsersPerTTI       = 8, ...
    MUMIMOConfigDL          = struct('MaxNumUsersPaired',4,'MaxNumLayers',8, ...
                                     'MinNumRBs',2,'SemiOrthogonalityFactor',0.5,'MinCQI',1), ...
    CSIMeasurementSignalDL  = "CSI-RS", ...
    LinkAdaptationConfigDL  = oLLA);

UEs = nrUE( ...
    Name                = "UE-" + (1:4), ...
    Position            = [100 0 30; 150 50 30; 80 -60 30; 200 0 30], ...
    ReceiveGain         = 0, ...
    NumTransmitAntennas = 4, ...
    NumReceiveAntennas  = 4);

gNB.PMICQIMode = "Wideband";
connectUE(gNB, UEs, FullBufferTraffic="DL", CSIReportPeriodicity=10);

addNodes(sim, gNB);
addNodes(sim, UEs);

channelConfig    = struct(DelayProfile="CDL-B", DelaySpread=100e-9, MaximumDopplerShift=5);
channels         = hNRCreateCDLChannels(channelConfig, gNB, UEs);
customCh         = hNRCustomChannelModel(channels);
addChannelModel(sim, @customCh.applyChannelModel);

fprintf('\n=== Wiring test: 4T, 4 UEs, 3 frames ===\n');
fprintf('Pass: [OLLA] lines appear  |  Fail: no [OLLA] lines\n\n');

tic
run(sim, 3 * 1e-2);
fprintf('\nRuntime: %.1f s\n', toc);
fprintf('\nIf [OLLA] lines appeared => OLLA wired correctly (fix confirmed).\n');
fprintf('If no [OLLA] lines => LinkAdaptationConfigDL still not reaching the callback.\n');
